[buildPlans.iosevka-comfy]       # <iosevka-comfy> is your plan name
family = "Iosevka Comfy"         # Font menu family name
spacing = "normal"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`

###################################################################################################
# Configure variants

# # Optional; Whether to inherit a `ss##` variant
# [buildPlans.iosevka-comfy.variants]
# inherits = "ss01"

# Optional; Configure single character's variant
[buildPlans.iosevka-comfy.variants.design]
cv01 = 1    # a cap straight
cv02 = 1    # b cap straight
cv03 = 2    # d cap curly
cv04 = 1    # g cap toothed
cv05 = 3    # i cap short serifs
cv06 = 2    # j cap serified
cv07 = 1    # k cap straight
cv08 = 1    # m cap short middle leg
cv09 = 2    # q cap straight
cv10 = 1    # r cap straight
cv11 = 1    # y cap straight
cv13 = 1    # b toothed
cv14 = 1    # d toothed
cv17 = 1    # h straight
cv18 = 10   # i serified flat tailed
cv19 = 4    # j flat hook serified
cv21 = 10   # l serified flat tailed
cv26 = 8    # r compact
cv27 = 3    # t flat hook
cv32 = 5    # y cursive flat terminal hook
cv36 = 2    # 0 dotted
cv38 = 2    # 3 arched
cv41 = 1    # 7 straight
cv43 = 2    # tilde low
cv44 = 2    # asterisk low
cv45 = 1    # underscore right below baseline
cv47 = 1    # uptick high
cv48 = 1    # parentheses normal slope
cv49 = 1    # braces straight (simplified)
cv50 = 1    # column straight
cv53 = 1    # dollar open
cv54 = 1    # percent dots
cv55 = 1    # bar natural slope
cv56 = 2    # equal-or-{higher,lower} slanted
cv57 = 1    # single quote straight
cv58 = 1    # grave/backtick straight
cv62 = 2    # 8 two circles

# Optional; Configure single character's variant for Upright and Oblique; Overrides [design]
[buildPlans.iosevka-comfy.variants.upright]
cv12 = 1    # a double storey
cv15 = 13   # f serifless bottom flat top crossbar at x height
cv16 = 7    # g single storey flat hook earless
cv20 = 1    # k straight
cv22 = 9    # m earless double arch
cv23 = 3    # n earless straight
cv24 = 2    # p earless
cv25 = 3    # q earless
cv28 = 1    # u straight
cv29 = 1    # v straight
cv30 = 1    # w straight
cv31 = 1    # x straight
cv33 = 1    # z straight
cv34 = 2    # eszet greek-beta-like
cv35 = 1    # λ straight
cv37 = 2    # 1 serified with base
cv39 = 3    # 4 semi-open contour
cv40 = 3    # 6 straight
cv42 = 3    # 9 straight
cv51 = 2    # ampersand open top
cv52 = 1    # at threefold
cv59 = 1    # e straight
cv61 = 1    # 2 straight

# Optional; Configure single character's variant for Italic only; Overrides [design]
[buildPlans.iosevka-comfy.variants.italic]
cv12 = 8    # a single storey earless tailed
cv15 = 11   # f extended flat top bottom hook
cv16 = 6    # g single storey flat hook
cv20 = 2    # k curly
cv22 = 2    # m shortleg straight
cv23 = 1    # n straight
cv24 = 1    # p straight
cv25 = 1    # q straight
cv28 = 4    # u tailed
cv29 = 2    # v curly
cv30 = 2    # w curly
cv31 = 2    # x curly
cv33 = 4    # z curly
cv34 = 3    # eszet Ss ligature
cv35 = 2    # λ curly
cv37 = 1    # 1 serified no base
cv39 = 1    # 4 closed contour crossing
cv40 = 1    # 6 closed contour
cv42 = 1    # 9 closed contour
cv51 = 4    # ampersand open top toothed
cv52 = 3    # at short
cv59 = 1    # e curly
cv61 = 2    # 2 curly

# End variant section
###################################################################################################

###################################################################################################
# Configure ligations

[buildPlans.iosevka-comfy.ligations]
inherits = "default-calt"   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set

# End ligation section
###################################################################################################


###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.iosevka-comfy.weights.light]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-comfy.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-comfy.weights.semibold]
shape = 600
menu  = 600
css   = 600

[buildPlans.iosevka-comfy.weights.bold]
shape = 700
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slopes would be built.

[buildPlans.iosevka-comfy.slopes]
upright = "normal"
italic = "italic"

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-comfy.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

# [buildPlans.iosevka-comfy.widths.extended]
# shape = 576
# menu  = 7
# css   = "expanded"

# End width section
###################################################################################################

###################################################################################################
# Character Exclusion
# Specify character ranges in the section below to exclude certain characters from the font being
# built. Remove this section when this feature is not needed.

[buildPlans.iosevka-comfy.exclude-chars]
ranges = [[10003, 10008]]

# End character exclusion
###################################################################################################

###################################################################################################
# Compatibility Ligatures
# Certain applications like Emacs does not support proper programming liagtures provided by
# OpenType, but can support ligatures provided by PUA codepoints. Therefore you can edit the
# following section to build PUA characters that are generated from the OpenType ligatures.
# Remove this section when compatibility ligatures are not needed.

[[buildPlans.iosevka-comfy.compatibility-ligatures]]
unicode = 57600 # 0xE100
featureTag = 'calt'
sequence = '<*>'

# End compatibility ligatures section
###################################################################################################

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

# [buildPlans.iosevka-comfy.metric-override]
# leading = 1250                 # default: 1250
# parensize= 966                 # default: 966
# xheight = 530                  # default: 530
# symbolMid= 340                 # default: 340
# cap = 735                      # default: 735
# winMetricAscenderPad = 0
# winMetricDescenderPad = 0
# powerlineScaleY = 1
# powerlineScaleX = 1
# powerlineShiftY = 0
# powerlineShiftX = 0

# End metric override section
###################################################################################################
